# Generated by Django 4.1.7 on 2023-03-01 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_post_options_postparagraph_postimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postimage",
            name="paragraph",
        ),
        migrations.AddField(
            model_name="postimage",
            name="post",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="posts.post",
            ),
        ),
    ]
