# Generated by Django 4.1.7 on 2023-03-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_remove_postparagraph_post_post_content_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="content",
        ),
    ]
