# Generated by Django 4.1.7 on 2023-03-01 06:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_alter_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
    ]
